import { expect, test } from '@playwright/test'

test('renders a seven-tenant mixed coverage story', async ({ page }) => {
  await page.route('**/api/module/manifest', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ protocolVersion: '1.0', moduleId: 'experiencia-digital', releaseStage: 'STAGE', dataEnvironment: 'PRODUCTION', freshnessMode: 'LIVE', clearance: 'ACADEMIC_PRIVATE', tenantScope: 'ALL_TENANTS' }) }))
  await page.route('**/api/experience**', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ generatedAt: '2026-08-12T18:00:00Z', from: '2026-07-12', to: '2026-08-12', tenants: [tenant('carlsjr', 'Carls Jr', 'AVAILABLE'), tenant('emerson', 'Emerson', 'NO_DATA'), tenant('valledelencino', 'Valle del Encino', 'NOT_SUPPORTED'), tenant('mcdonalds', "McDonald's", 'UNAVAILABLE'), tenant('mcdonalds-cdp', "McDonald's CDP", 'NO_DATA'), tenant('smartfit', 'SmartFit', 'NO_DATA'), tenant('bafar-poc-gabinete', 'Bafar POC Gabinete', 'NO_DATA')] }) }))
  await page.goto('/')
  await expect(page.getByText('Modulo · STAGE')).toBeVisible()
  await expect(page.getByText('Cobertura parcial', { exact: true })).toBeVisible()
  await expect(page.getByText('Sin cobertura', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Tiempo conectado diario por UserId' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Espera diaria por click' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Uptime, latencia y timeouts por servicio' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Detalle independiente por URL' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})

function tenant(id: string, name: string, status: string) {
  const users = { evaluatedUserDays: status === 'AVAILABLE' ? 10 : 0, sessionUserDays: status === 'AVAILABLE' ? 8 : 0, completeInteractions: status === 'AVAILABLE' ? 7 : 0, avgSessionSeconds: status === 'AVAILABLE' ? 80 : null, avgLatencyMs: status === 'AVAILABLE' ? 250 : null, maxP95LatencyMs: status === 'AVAILABLE' ? 500 : null, slowUserDays: 0 }
  const availability = { observedServiceDays: status === 'AVAILABLE' ? 10 : 0, avgUptimePercentage: status === 'AVAILABLE' ? 99.5 : null, avgLatencySeconds: status === 'AVAILABLE' ? .2 : null, maxP95LatencySeconds: status === 'AVAILABLE' ? .5 : null, timeoutDays: 0, currentDownServices: 0, latestDate: status === 'AVAILABLE' ? '2026-08-12' : null }
  return { tenantId: id, tenantName: name, coverageStatus: status, missingSources: status === 'AVAILABLE' ? ['observability.factUrlAvailabilityDaily'] : [], current: { users, availability }, previous: { users, availability }, userDaily: status === 'AVAILABLE' ? [{ metricDate: '2026-08-11', usersEvaluated: 1, connectedUsers: 1, completeInteractions: 1, totalTimeConnected: 1800, avgLatencyMs: 420, maxP95LatencyMs: 700 }, { metricDate: '2026-08-12', usersEvaluated: 1, connectedUsers: 1, completeInteractions: 1, totalTimeConnected: 2700, avgLatencyMs: 650, maxP95LatencyMs: 1100 }] : [], users: status === 'AVAILABLE' ? [{ userId: 'user-1', displayName: 'Operador Centro', userName: 'operador.centro', position: 'Gerencia', daysEvaluated: 2, completeInteractions: 2, timeConnectedSeconds: 4500, avgSessionSeconds: 2250, maxSessionSeconds: 2700, avgLatencyMs: 535, p95LatencyMs: 1100, lastActivityDate: '2026-08-12' }] : [], userTimeline: status === 'AVAILABLE' ? [{ userId: 'user-1', metricDate: '2026-08-11', displayName: 'Operador Centro', userName: 'operador.centro', madeCompleteInteraction: true, timeConnectedSeconds: 1800, avgLatencyMs: 420, p95LatencyMs: 700 }, { userId: 'user-1', metricDate: '2026-08-12', displayName: 'Operador Centro', userName: 'operador.centro', madeCompleteInteraction: true, timeConnectedSeconds: 2700, avgLatencyMs: 650, p95LatencyMs: 1100 }] : [], endpoints: status === 'AVAILABLE' ? [{ url: 'https://app.sidon.mx', uptimePercentage: 99.5, avgLatencySeconds: .2, latency95thPercentileSeconds: .5, upDays: 2, timeoutDays: 0, observedDays: 2, currentIsUp: true, currentTimeouts: false, latestDate: '2026-08-12' }] : [], availabilityDaily: status === 'AVAILABLE' ? [{ url: 'https://app.sidon.mx', metricDate: '2026-08-11', uptimePercentage: 99.2, avgLatencySeconds: .22, latency95thPercentileSeconds: .55, up: true, timeoutsPresent: false }, { url: 'https://app.sidon.mx', metricDate: '2026-08-12', uptimePercentage: 99.8, avgLatencySeconds: .18, latency95thPercentileSeconds: .45, up: true, timeoutsPresent: false }] : [], errorCode: status === 'UNAVAILABLE' ? 'TENANT_QUERY_FAILED' : null }
}
