import { expect, test } from '@playwright/test'

test('renders device risk with scoring evidence', async ({ page }) => {
  await page.route('**/api/module/manifest', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ protocolVersion: '1.0', moduleId: 'dispositivos', releaseStage: 'PRODUCTION', dataEnvironment: 'PRODUCTION', freshnessMode: 'LIVE', clearance: 'ACADEMIC_PRIVATE', tenantScope: 'ALL_TENANTS' }) }))
  const summary = { devicesObserved: 1, avgHealthScore: 42, attentionDevices: 1, criticalDevices: 1, degradingDevices: 1, avgFailureRiskScore: .91, avgConfidenceScore: .88, latestDate: '2026-08-12', latestModifiedAt: '2026-08-12T18:00:00Z' }
  const device = { deviceId: '11111111-1111-1111-1111-111111111111', locationId: '22222222-2222-2222-2222-222222222222', subLocationId: '33333333-3333-3333-3333-333333333333', deviceName: 'Cuarto frío principal', deviceType: 'Cuarto frío', equipmentKind: 'CUARTO_FRIO', localDate: '2026-08-12', healthScore: 42, operationalState: 'CRITICAL', worstHourlyState: 'CRITICAL', criticalHours: 2, degradedHours: 1, watchHours: 0, eventMinutes: 45, openEvents: 1, sevenDayHealthScore: 60, thirtyDayHealthScore: 70, trendDirection: 'DEGRADING', confidenceScore: 88, peerPercentileRisk: 95, failureRiskScore: .91, dominantReasonCode: 'HIGH_FAILURE_RISK', recommendedAction: 'Inspeccionar equipo', evidenceJson: '{}', featureSetVersion: 'v1', scoringVersion: 'score-v1', modelVersion: null, modifiedAt: '2026-08-12T18:00:00Z' }
  const hour = { deviceId: device.deviceId, locationId: device.locationId, subLocationId: device.subLocationId, deviceName: device.deviceName, deviceType: device.deviceType, localTimeSpan: '2026-08-12T09:00:00', healthScore: 42, operationalState: 'CRITICAL', trendDirection: 'DEGRADING', confidenceScore: 88, coverageScore: 92, expectedValueComplianceScore: 40, sensorReliabilityScore: 72, eventStabilityScore: 55, behaviorStabilityScore: 64, peerAlignmentScore: 70, failureRiskScore: .91, dominantReasonCode: 'HIGH_FAILURE_RISK', recommendedAction: 'Inspeccionar equipo', evidenceJson: '{}', featureSetVersion: 'v1', scoringVersion: 'score-v1', modelVersion: null, modifiedAt: '2026-08-12T18:00:00Z' }
  await page.route('**/api/devices/detail?*', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ generatedAt: '2026-08-12T18:00:00Z', device: { tenantId: 'carlsjr', deviceId: device.deviceId, locationId: device.locationId, subLocationId: device.subLocationId, localDate: device.localDate }, operationalHours: [hour, { ...hour, localTimeSpan: '2026-08-12T10:00:00', healthScore: 55, failureRiskScore: .72, operationalState: 'DEGRADED' }], measurements: [{ sensorId: 'sensor-1', sensorName: 'Temperatura retorno', sensorType: 'Temperatura', localTimeSpan: '2026-08-12T09:00:00', measurementValue: 12, measurementStdDev: .3, anomalies: 1, readingsCount: 6, expectedMin: 2, expectedMax: 8, expectedSchedules: '00:00-23:59 1-7', averageOutsideExpected: true, modifiedAt: '2026-08-12T10:00:00Z' }], events: [{ sensorId: 'sensor-1', sensorName: 'Temperatura retorno', sensorType: 'Temperatura', localTimeSpan: '2026-08-12T09:00:00', value: 1, eventMinutes: 45, completed: false }], audits: [{ sensorId: 'sensor-1', sensorName: 'Temperatura retorno', sensorType: 'Temperatura', localTimeSpan: '2026-08-12T09:00:00', readingsCount: 0, late: true, connectionLost: true, lastReadingAt: '2026-08-12T08:00:00Z', connectionLostAt: '2026-08-12T09:00:00Z', minutesWithoutReadings: 60 }], sensors: [{ sensorId: 'sensor-1', sensorName: 'Temperatura retorno', sensorType: 'Temperatura', active: true, expectedMin: 2, expectedMax: 8, startTime: '00:00:00', endTime: '23:59:59', scheduledDays: '1-7' }] }) }))
  await page.route('**/api/devices?*', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ generatedAt: '2026-08-12T18:00:00Z', from: '2026-07-12', to: '2026-08-12', tenants: [{ tenantId: 'carlsjr', tenantName: 'Carls Jr', coverageStatus: 'AVAILABLE', missingSources: [], current: summary, previous: summary, devices: [device], daily: [{ ...device, localDate: '2026-08-11', healthScore: 58, failureRiskScore: .7 }, device], hourly: [hour, { ...hour, localTimeSpan: '2026-08-12T10:00:00', healthScore: 55, failureRiskScore: .72 }], errorCode: null }] }) }))
  await page.goto('/')
  await expect(page.getByText('1 dispositivos están en estado crítico.')).toBeVisible()
  await expect(page.getByText('score-v1')).toBeVisible()
  await expect(page.getByText('Cuarto frío', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Salud diaria por dispositivo' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Salud horaria por dispositivo' })).toBeVisible()
  await expect(page.locator('.evidence > .table-wrap > table > thead th')).toHaveText(['Tenant y dispositivo', 'Familia', 'Estado', 'Salud / riesgo', 'Confianza', 'Tendencia', 'Razón y acción'])
  await page.getByText('Abrir evidencia hora a hora').click()
  await expect(page.getByRole('heading', { name: 'Por que el dispositivo recibio este diagnostico' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Temperatura retorno · Temperatura' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Evidencia hora por hora' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Evidencia que sostiene la recomendacion' })).toHaveCount(0)
  await expect(page.locator('.hourly-status-table thead th')).toContainText(['Hora', 'Dispositivo', 'Salud / riesgo', 'Confianza', 'Causa dominante'])
  await expect(page.locator('.hourly-status-table tbody tr').first()).toHaveAttribute('title', 'Recomendación: Inspeccionar equipo')
  await expect(page.getByText('Riesgo de falla', { exact: true }).first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
})
