import { useEffect, useMemo, useState } from 'react'
import { continuity, delta, statusLabel } from './metrics'
import type { DashboardResponse, HostContext, Manifest, TenantResult } from './types'

const number = (value: number | null, digits = 0) => value == null ? '—' : new Intl.NumberFormat('es-MX', { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value)
const baseline = (value: number | null) => value == null ? 'Sin baseline comparable' : `${value > 0 ? '+' : ''}${number(value, 1)} pp vs. periodo anterior`

export default function App({ context }: { context: HostContext }) {
  const [manifest, setManifest] = useState<Manifest | null>(null); const [data, setData] = useState<DashboardResponse | null>(null); const [state, setState] = useState<'loading'|'ready'|'error'>('loading')
  useEffect(() => { let active = true; void (async () => { setState('loading'); try { const token = await context.auth.getAccessToken('lecturas'); const query = new URLSearchParams({ from: context.period.from, to: context.period.to }); if (context.tenantIds.length) query.set('tenant', context.tenantIds.join(',')); const headers = token ? { Authorization: `Bearer ${token}` } : undefined; const [manifestResponse, dataResponse] = await Promise.all([fetch(`${context.apiBaseUrl}/api/module/manifest`), fetch(`${context.apiBaseUrl}/api/readings?${query}`, { headers })]); if (!manifestResponse.ok || !dataResponse.ok) throw new Error('load_failed'); const [nextManifest, nextData] = await Promise.all([manifestResponse.json() as Promise<Manifest>, dataResponse.json() as Promise<DashboardResponse>]); if (active) { setManifest(nextManifest); setData(nextData); setState('ready') } } catch { if (active) setState('error') } })(); return () => { active = false } }, [context])
  const available = useMemo(() => data?.tenants.filter((tenant) => tenant.coverageStatus === 'AVAILABLE') ?? [], [data]); const currentContinuity = continuity(available); const previousContinuity = continuity(available, true); const disconnected = available.reduce((sum, tenant) => sum + tenant.current.disconnectedSensors, 0); const late = available.reduce((sum, tenant) => sum + tenant.current.lateSensors, 0); const exceptions = available.flatMap((tenant) => tenant.exceptions.map((item) => ({ ...item, tenantName: tenant.tenantName }))).sort((left, right) => Number(right.disconnected) - Number(left.disconnected) || (right.minutesWithoutReadings ?? 0) - (left.minutesWithoutReadings ?? 0))
  if (state === 'loading') return <section className="state"><strong>Consultando continuidad de lecturas</strong><span>Priorizando desconexiones por tenant.</span></section>
  if (state === 'error' || !manifest || !data) return <section className="state error"><strong>Lecturas no esta disponible</strong><span>La falla queda aislada dentro de este modulo.</span></section>
  const verdict = disconnected ? `${disconnected} sensores estan desconectados.` : late ? `${late} sensores entregan lecturas tardias.` : available.length ? 'Los sensores observados mantienen continuidad.' : 'No existe evidencia suficiente para evaluar continuidad.'
  return <main className="app">
    <header><div><span className="eyebrow">ICOS · TEMPERATURA</span><h1>Continuidad de lecturas</h1><p>Excepciones primero; evidencia por sensor despues.</p></div><div className="badges"><span>Modulo · {manifest.releaseStage}</span><span>Datos · {manifest.dataEnvironment} / {manifest.freshnessMode}</span><span>Alcance · 7 tenants</span><span>Clearance · {manifest.clearance}</span></div></header>
    <section className={`verdict ${disconnected ? 'critical' : late ? 'warning' : available.length ? 'healthy' : 'neutral'}`}><div><span>N1 · ESTADO OBSERVADO</span><strong>{verdict}</strong></div><p>{disconnected ? 'Atienda primero sensores sin conexion y confirme la ultima lectura.' : late ? 'Revise si la tardanza es local o compartida antes de intervenir.' : 'Que sigue: vigile frescura y cambios frente al periodo anterior.'}</p></section>
    <section className="metrics"><article><span>Continuidad actual</span><strong>{number(currentContinuity, 1)}%</strong><p>{baseline(delta(currentContinuity, previousContinuity))}</p></article><article><span>Desconectados</span><strong>{disconnected}</strong><p>Estado mas reciente del periodo</p></article><article><span>Lectura tardia</span><strong>{late}</strong><p>Puede coexistir con desconexion</p></article><article><span>Tenants con evidencia</span><strong>{available.length}/{data.tenants.length}</strong><p>Ausencia no se interpreta como cero</p></article></section>
    <section className="coverage"><div className="section-heading"><div><span>RED</span><h2>Cobertura y continuidad por tenant</h2></div><small>Peor condicion primero</small></div>{[...data.tenants].sort((left, right) => right.current.disconnectedSensors - left.current.disconnectedSensors).map((tenant) => <TenantRow key={tenant.tenantId} tenant={tenant} />)}</section>
    <section className="exceptions"><div className="section-heading"><div><span>EVIDENCIA</span><h2>Sensores que requieren atencion</h2></div><small>{exceptions.length} de hasta 50 por tenant</small></div>{exceptions.length ? <div className="table-wrap"><table><thead><tr><th>Tenant y ubicacion</th><th>Equipo y sensor</th><th>Estado</th><th>Minutos sin lectura</th><th>Ultima lectura UTC</th></tr></thead><tbody>{exceptions.map((item) => <tr key={`${item.tenantName}-${item.sensorId}`}><td><strong>{item.tenantName}</strong><span>{item.locationName}</span></td><td><strong>{item.deviceName}</strong><span>{item.sensorName}</span></td><td><b className={item.disconnected ? 'critical-pill' : 'warning-pill'}>{item.disconnected ? 'Desconectado' : 'Tardio'}</b></td><td>{number(item.minutesWithoutReadings, 0)}</td><td>{item.lastReadingAt ? new Intl.DateTimeFormat('es-MX', { dateStyle: 'short', timeStyle: 'short', timeZone: 'UTC' }).format(new Date(item.lastReadingAt)) : '—'}</td></tr>)}</tbody></table></div> : <div className="empty"><strong>Sin excepciones en el alcance disponible</strong><span>El estado sano permanece resumido.</span></div>}</section>
    <section className="next"><div><span>N2 · RECOMENDACION</span><h2>{disconnected ? 'Recupere conexion empezando por la mayor brecha.' : late ? 'Valide transporte y frecuencia de lectura.' : 'Mantenga monitoreo de frescura.'}</h2></div><p>Impacto esperado: reducir periodos sin evidencia sin confundir falta de cobertura con una operacion saludable.</p></section>
    <footer><span>Generado {new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(data.generatedAt))}</span><span>{context.timezone}</span></footer>
  </main>
}

function TenantRow({ tenant }: { tenant: TenantResult }) { if (tenant.coverageStatus !== 'AVAILABLE') return <article className="tenant unavailable"><div><strong>{tenant.tenantName}</strong><span>{statusLabel(tenant.coverageStatus)}</span></div><p>{tenant.coverageStatus === 'NO_DATA' ? 'La tabla existe sin filas en el periodo.' : tenant.coverageStatus === 'NOT_SUPPORTED' ? 'El fact de lecturas no existe.' : 'Conexion o consulta no disponible.'}</p></article>; const score = tenant.current.sensorsObserved ? tenant.current.healthySensors / tenant.current.sensorsObserved * 100 : null; return <article className="tenant"><div><strong>{tenant.tenantName}</strong><span>{tenant.missingSources.length ? 'Cobertura parcial' : 'Disponible'}</span></div><div><span>Continuidad <b>{number(score, 1)}%</b></span><span>Observados <b>{tenant.current.sensorsObserved}</b></span><span>Desconectados <b>{tenant.current.disconnectedSensors}</b></span><span>Tardios <b>{tenant.current.lateSensors}</b></span></div><i><b style={{ width: `${score ?? 0}%` }} /></i></article> }
