import { useEffect, useMemo, useState } from 'react'
import { communication, continuity, delta, statusLabel } from './metrics'
import type { DashboardResponse, HostContext, Manifest, TenantResult } from './types'

const number = (value: number | null, digits = 0) => value == null ? '—' : new Intl.NumberFormat('es-MX', { minimumFractionDigits: digits, maximumFractionDigits: digits }).format(value)
const baseline = (value: number | null) => value == null ? 'Sin baseline comparable' : `${value > 0 ? '+' : ''}${number(value, 1)} pp vs. periodo anterior`
const chartPoints = (values: number[], maximum: number) => values.map((value, index) => `${values.length === 1 ? 50 : index / Math.max(1, values.length - 1) * 100},${92 - Math.min(1, value / Math.max(1, maximum)) * 78}`).join(' ')

export default function App({ context }: { context: HostContext }) {
  const [manifest, setManifest] = useState<Manifest | null>(null); const [data, setData] = useState<DashboardResponse | null>(null); const [state, setState] = useState<'loading'|'ready'|'error'>('loading')
  const [hoveredHourIndex, setHoveredHourIndex] = useState<number | null>(null)
  useEffect(() => { let active = true; void (async () => { setState('loading'); try { const token = await context.auth.getAccessToken('lecturas'); const query = new URLSearchParams({ from: context.period.from, to: context.period.to }); if (context.tenantIds.length) query.set('tenant', context.tenantIds.join(',')); const headers = token ? { Authorization: `Bearer ${token}` } : undefined; const [manifestResponse, dataResponse] = await Promise.all([fetch(`${context.apiBaseUrl}/api/module/manifest`), fetch(`${context.apiBaseUrl}/api/readings?${query}`, { headers })]); if (!manifestResponse.ok || !dataResponse.ok) throw new Error('load_failed'); const [nextManifest, nextData] = await Promise.all([manifestResponse.json() as Promise<Manifest>, dataResponse.json() as Promise<DashboardResponse>]); if (active) { setManifest(nextManifest); setData(nextData); setState('ready') } } catch { if (active) setState('error') } })(); return () => { active = false } }, [context])
  const available = useMemo(() => data?.tenants.filter((tenant) => tenant.coverageStatus === 'AVAILABLE') ?? [], [data]); const averageCommunication = communication(available); const currentContinuity = continuity(available); const previousContinuity = continuity(available, true); const observed = available.reduce((sum, tenant) => sum + tenant.current.sensorsObserved, 0); const disconnected = available.reduce((sum, tenant) => sum + tenant.current.disconnectedSensors, 0); const late = available.reduce((sum, tenant) => sum + tenant.current.lateSensors, 0)
  const allSensors = available.flatMap((tenant) => (tenant.sensors ?? []).map((sensor) => ({ ...sensor, tenantId: tenant.tenantId, tenantName: tenant.tenantName })))
  const sensors = allSensors.filter((sensor) => (!context.filters?.location || sensor.locationName === context.filters.location) && (!context.filters?.device || sensor.deviceName === context.filters.device) && (!context.filters?.sensor || sensor.sensorId === context.filters.sensor))
  const visibleSensorKeys = new Set(sensors.map((sensor) => `${sensor.tenantId}|${sensor.sensorId}`))
  const exceptions = available.flatMap((tenant) => tenant.exceptions.map((item) => ({ ...item, tenantId: tenant.tenantId, tenantName: tenant.tenantName }))).filter((item) => (!context.filters?.location || item.locationName === context.filters.location) && (!context.filters?.device || item.deviceName === context.filters.device) && (!context.filters?.sensor || item.sensorId === context.filters.sensor)).sort((left, right) => Number(right.disconnected) - Number(left.disconnected) || (right.minutesWithoutReadings ?? 0) - (left.minutesWithoutReadings ?? 0))
  const timeline = available.flatMap((tenant) => (tenant.timeline ?? []).map((row) => ({ ...row, tenantId: tenant.tenantId }))).filter((row) => visibleSensorKeys.has(`${row.tenantId}|${row.sensorId}`))
  const hours = [...new Set(timeline.map((row) => row.timeSpan))].sort()
  const timelineRows = new Map(timeline.map((row) => [`${row.tenantId}|${row.sensorId}|${row.timeSpan}`, row]))
  const hourlyMap = new Map<string, { timeSpan: string; sensors: number; totalReadings: number; lostSensors: number; lateSensors: number }>()
  timeline.forEach((row) => { const current = hourlyMap.get(row.timeSpan) ?? { timeSpan: row.timeSpan, sensors: 0, totalReadings: 0, lostSensors: 0, lateSensors: 0 }; current.sensors += 1; current.totalReadings += row.readingsCount; current.lostSensors += row.disconnected ? 1 : 0; current.lateSensors += row.late ? 1 : 0; hourlyMap.set(row.timeSpan, current) })
  const hourly = [...hourlyMap.values()].sort((left, right) => left.timeSpan.localeCompare(right.timeSpan))
  const maxHourlyReadings = Math.max(1, ...hourly.map((row) => row.totalReadings))
  const sensorNames = new Map(sensors.map((sensor) => [`${sensor.tenantId}|${sensor.sensorId}`, sensor.sensorName]))
  const readingsByHour = new Map<string, typeof timeline>()
  timeline.forEach((row) => { const rows = readingsByHour.get(row.timeSpan) ?? []; rows.push(row); readingsByHour.set(row.timeSpan, rows) })
  const topSensorsByHour = new Map(hourly.map((row) => [row.timeSpan, [...(readingsByHour.get(row.timeSpan) ?? [])].sort((left, right) => right.readingsCount - left.readingsCount).slice(0, 3).map((item) => ({ name: sensorNames.get(`${item.tenantId}|${item.sensorId}`) ?? item.sensorId, readings: item.readingsCount }))]))
  const hoveredHour = hoveredHourIndex == null ? null : hourly[hoveredHourIndex]
  const latestHour = hours.at(-1)
  if (state === 'loading') return <section className="state"><strong>Consultando continuidad de lecturas</strong><span>Priorizando desconexiones por tenant.</span></section>
  if (state === 'error' || !manifest || !data) return <section className="state error"><strong>Lecturas no esta disponible</strong><span>La falla queda aislada dentro de este modulo.</span></section>
  const verdict = disconnected ? `${disconnected} sensores estan desconectados.` : late ? `${late} sensores entregan lecturas tardias.` : available.length ? 'Los sensores observados mantienen continuidad.' : 'No existe evidencia suficiente para evaluar continuidad.'
  return <main className="app">
    <div className="page-heading"><header><div><span className="eyebrow">ICOS · TEMPERATURA</span><h1>Continuidad de lecturas</h1><p>Excepciones primero; evidencia por sensor después.</p></div><div className="badges"><span className={`release-${manifest.releaseStage.toLowerCase()}`}>Módulo · {manifest.releaseStage}</span><span className={`data-${manifest.dataEnvironment.toLowerCase()}`}>Datos · {manifest.dataEnvironment}</span></div></header><section className={`verdict ${disconnected ? 'critical' : late ? 'warning' : available.length ? 'healthy' : 'neutral'}`}><div><span>N1 · ESTADO OBSERVADO</span><strong>{verdict}</strong></div><p>{disconnected ? 'Atienda primero sensores sin conexion y confirme la ultima lectura.' : late ? 'Revise si la tardanza es local o compartida antes de intervenir.' : 'Que sigue: vigile frescura y cambios frente al periodo anterior.'}</p></section></div>
    <section className="metrics"><article><span>Comunicación promedio</span><strong>{number(averageCommunication, 1)}%</strong><p>Intervalos con lectura en el periodo</p></article><article><span>Sensores observados</span><strong>{observed}</strong><p>Denominador del estado actual</p></article><article><span>Continuidad actual</span><strong>{number(currentContinuity, 1)}%</strong><p>{baseline(delta(currentContinuity, previousContinuity))}</p></article><article><span>Desconectados</span><strong>{disconnected}</strong><p>Estado mas reciente del periodo</p></article><article><span>Lectura tardia</span><strong>{late}</strong><p>Puede coexistir con desconexion</p></article><article><span>Tenants con evidencia</span><strong>{available.length}/{data.tenants.length}</strong><p>Ausencia no se interpreta como cero</p></article></section>
    {context.tenantIds.length !== 1 && <section className="coverage"><div className="section-heading"><div><span>RED</span><h2>Cobertura y continuidad por tenant</h2></div><small>Peor condicion primero</small></div>{[...data.tenants].sort((left, right) => right.current.disconnectedSensors - left.current.disconnectedSensors).map((tenant) => <TenantRow key={tenant.tenantId} tenant={tenant} />)}</section>}
    <section className="timeline-panel"><div className="section-heading"><div><span>HISTORICO HORA A HORA</span><h2>Lecturas reportadas por sensor</h2></div><small>{hours.length} horas · {sensors.length} sensores</small></div><div className="timeline-legend"><span><i className="zero" />0</span><span><i className="mid" />3</span><span><i className="high" />6+</span><span><i className="loss" />Perdida</span></div>{sensors.length && hours.length ? <div className="timeline-scroll"><div className="timeline-matrix" style={{ minWidth: `${Math.max(760, hours.length * 15 + 190)}px` }}><div className="timeline-row timeline-header" style={{ gridTemplateColumns: `180px repeat(${hours.length}, minmax(12px, 1fr))` }}><strong>Sensor</strong>{hours.map((hour, index) => <span key={hour}>{index % Math.max(1, Math.ceil(hours.length / 10)) === 0 ? new Intl.DateTimeFormat('es-MX', { month: 'short', day: '2-digit', hour: '2-digit' }).format(new Date(hour)) : ''}</span>)}</div>{sensors.map((sensor) => <div className="timeline-row" key={`${sensor.tenantId}-${sensor.sensorId}`} style={{ gridTemplateColumns: `180px repeat(${hours.length}, minmax(12px, 1fr))` }}><div className="timeline-label"><i className={latestHour && timelineRows.get(`${sensor.tenantId}|${sensor.sensorId}|${latestHour}`)?.disconnected ? 'latest-status loss' : 'latest-status healthy'} title="Estado de la última hora" /><strong>{sensor.sensorName}</strong><span>{sensor.tenantName} · {sensor.deviceName}</span></div>{hours.map((hour) => { const row = timelineRows.get(`${sensor.tenantId}|${sensor.sensorId}|${hour}`); const intensity = row ? .05 + Math.min(row.readingsCount, 6) / 6 * .9 : .03; return <span key={hour} className={`timeline-cell ${row?.disconnected ? 'loss' : ''}`} style={!row?.disconnected ? { backgroundColor: `rgba(20,135,112,${intensity})` } : undefined} title={row ? `${new Date(row.localTimeSpan).toLocaleString('es-MX')}: ${row.readingsCount} lecturas${row.disconnected ? ` · perdida · ${row.minutesWithoutReadings ?? 0} min` : row.late ? ' · tardanza' : ''}` : `${new Date(hour).toLocaleString('es-MX')}: sin registro`} /> })}</div>)}</div></div> : <div className="empty"><strong>Sin historia horaria en el periodo</strong><span>La tabla de excepciones permanece disponible.</span></div>}</section>
    <section className="hourly-panel"><div className="section-heading"><div><span>VOLUMEN</span><h2>Lecturas totales por hora</h2></div><small>Pase el mouse para ver periodo, total y top 3</small></div>{hourly.length ? <div className="large-line-chart" onMouseLeave={() => setHoveredHourIndex(null)}><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Lecturas totales por hora">{[20, 40, 60, 80].map((y) => <line key={y} x1="0" y1={y} x2="100" y2={y} />)}<polygon className="readings-area" points={`0,92 ${chartPoints(hourly.map((row) => row.totalReadings), maxHourlyReadings)} 100,92`} /><polyline className="teal-line" points={chartPoints(hourly.map((row) => row.totalReadings), maxHourlyReadings)} />{hoveredHour && <line className="chart-crosshair" x1={hourly.length === 1 ? 50 : hoveredHourIndex! / (hourly.length - 1) * 100} y1="8" x2={hourly.length === 1 ? 50 : hoveredHourIndex! / (hourly.length - 1) * 100} y2="92" />}{hourly.map((row, index) => <rect className="chart-hit-area" key={row.timeSpan} x={index / hourly.length * 100} y="0" width={100 / hourly.length} height="100" onMouseEnter={() => setHoveredHourIndex(index)} />)}</svg>{hoveredHour && <div className="line-tooltip" role="tooltip" style={{ left: `${Math.min(86, Math.max(14, hourly.length === 1 ? 50 : hoveredHourIndex! / (hourly.length - 1) * 100))}%` }}><strong>{new Date(hoveredHour.timeSpan).toLocaleString('es-MX')}</strong><span>Total: {hoveredHour.totalReadings} lecturas</span><small>Top 3 sensores</small>{(topSensorsByHour.get(hoveredHour.timeSpan) ?? []).map((sensor) => <span key={sensor.name}>{sensor.name}: {sensor.readings}</span>)}</div>}<div className="event-strip">{hourly.map((row, index) => <span key={row.timeSpan} className={row.lostSensors ? 'loss' : row.lateSensors ? 'late' : 'healthy'} tabIndex={0} aria-label={`${new Date(row.timeSpan).toLocaleString('es-MX')}: ${row.totalReadings} lecturas`} onMouseEnter={() => setHoveredHourIndex(index)} onFocus={() => setHoveredHourIndex(index)} onBlur={() => setHoveredHourIndex(null)} />)}</div><div className="chart-labels">{hourly.map((row, index) => index % Math.max(1, Math.ceil(hourly.length / 7)) === 0 ? <span key={row.timeSpan}>{new Intl.DateTimeFormat('es-MX', { month: 'short', day: '2-digit', hour: '2-digit' }).format(new Date(row.timeSpan))}</span> : null)}</div></div> : <div className="empty"><strong>Sin volumen horario en el periodo</strong></div>}</section>
    <section className="exceptions"><div className="section-heading"><div><span>EVIDENCIA</span><h2>Sensores que requieren atencion</h2></div><small>{exceptions.length} de hasta 50 por tenant</small></div>{exceptions.length ? <div className="table-wrap"><table><thead><tr><th>Tenant y ubicacion</th><th>Equipo y sensor</th><th>Estado</th><th>Minutos sin lectura</th><th>Ultima lectura UTC</th></tr></thead><tbody>{exceptions.map((item) => <tr key={`${item.tenantName}-${item.sensorId}`}><td><strong>{item.tenantName}</strong><span>{item.locationName}</span></td><td><strong>{item.deviceName}</strong><span>{item.sensorName}</span></td><td><b className={item.disconnected ? 'critical-pill' : 'warning-pill'}>{item.disconnected ? 'Desconectado' : 'Tardio'}</b></td><td>{number(item.minutesWithoutReadings, 0)}</td><td>{item.lastReadingAt ? new Intl.DateTimeFormat('es-MX', { dateStyle: 'short', timeStyle: 'short', timeZone: 'UTC' }).format(new Date(item.lastReadingAt)) : '—'}</td></tr>)}</tbody></table></div> : <div className="empty"><strong>Sin excepciones en el alcance disponible</strong><span>El estado sano permanece resumido.</span></div>}</section>
    <section className="next"><div><span>N2 · RECOMENDACION</span><h2>{disconnected ? 'Recupere conexion empezando por la mayor brecha.' : late ? 'Valide transporte y frecuencia de lectura.' : 'Mantenga monitoreo de frescura.'}</h2></div><p>Impacto esperado: reducir periodos sin evidencia sin confundir falta de cobertura con una operacion saludable.</p></section>
    <footer><span>Generado {new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(data.generatedAt))}</span><span>{context.timezone}</span></footer>
  </main>
}

function TenantRow({ tenant }: { tenant: TenantResult }) { if (tenant.coverageStatus !== 'AVAILABLE') return <article className="tenant unavailable"><div><strong>{tenant.tenantName}</strong><span>{statusLabel(tenant.coverageStatus)}</span></div><p>{tenant.coverageStatus === 'NO_DATA' ? 'La tabla existe sin filas en el periodo.' : tenant.coverageStatus === 'NOT_SUPPORTED' ? 'El fact de lecturas no existe.' : 'Conexion o consulta no disponible.'}</p></article>; const score = tenant.current.sensorsObserved ? tenant.current.healthySensors / tenant.current.sensorsObserved * 100 : null; return <article className="tenant"><div><strong>{tenant.tenantName}</strong><span>{tenant.missingSources.length ? 'Cobertura parcial' : 'Disponible'}</span></div><div><span>Continuidad <b>{number(score, 1)}%</b></span><span>Observados <b>{tenant.current.sensorsObserved}</b></span><span>Desconectados <b>{tenant.current.disconnectedSensors}</b></span><span>Tardios <b>{tenant.current.lateSensors}</b></span></div><i><b style={{ width: `${score ?? 0}%` }} /></i></article> }
