export type HostContext = { protocolVersion: '1.0'; moduleId: string; locale: 'es-MX'; timezone: string; tenantIds: string[]; period: { from: string; to: string }; filters?: { location: string; device: string; sensor: string }; freshness: Freshness[]; identity: { subject: string; displayName: string; roles: string[]; permissions: string[]; tenantScope: string[] }; apiBaseUrl: string; auth: { getAccessToken: (moduleId: string) => Promise<string> }; navigate: (target: { moduleId: string; path?: string }) => void }
export type Freshness = { tenantId: string; tenantName: string; ingestionName: string; lastRunStatus: string | null; lastLoadedAt: string | null }
export type Manifest = { protocolVersion: '1.0'; moduleId: string; displayName: string; releaseStage: string; dataEnvironment: string; freshnessMode: string; clearance: string; tenantScope: string }
export type Summary = { sensorsObserved: number; healthySensors: number; disconnectedSensors: number; lateSensors: number; avgMinutesWithoutReadings: number | null; maxMinutesWithoutReadings: number | null; latestAuditAt: string | null; latestReadingAt: string | null }
export type SensorException = { sensorId: string; locationName: string; deviceName: string; sensorName: string; disconnected: boolean; late: boolean; minutesWithoutReadings: number | null; auditAt: string | null; lastReadingAt: string | null }
export type SensorHourly = { timeSpan: string; sensors: number; avgReadings: number | null; totalReadings: number; lostSensors: number; lateSensors: number }
export type SensorTimeline = { sensorId: string; timeSpan: string; localTimeSpan: string; readingsCount: number; late: boolean; disconnected: boolean; lastReadingAt: string | null; connectionLostAt: string | null; minutesWithoutReadings: number | null }
export type SensorAggregate = { sensorId: string; locationName: string; deviceName: string; sensorName: string; observedIntervals: number; totalReadings: number; avgReadings: number | null; lostIntervals: number; lateIntervals: number; healthPercentage: number | null; lastReadingAt: string | null; maxLossMinutes: number | null }
export type TenantResult = { tenantId: string; tenantName: string; coverageStatus: 'AVAILABLE' | 'NO_DATA' | 'NOT_SUPPORTED' | 'UNAVAILABLE'; missingSources: string[]; current: Summary; previous: Summary; exceptions: SensorException[]; hourly?: SensorHourly[]; timeline?: SensorTimeline[]; sensors?: SensorAggregate[]; errorCode: string | null }
export type DashboardResponse = { generatedAt: string; from: string; to: string; tenants: TenantResult[] }
